name: kusuka_moto
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.19.0 # Atualizado com a versão desejada
  pdf: ^3.6.0
  printing: ^5.10.0
  flutter_riverpod: ^2.3.0
  cloud_firestore: ^5.5.0
  firebase_auth: ^5.3.3  # Verifique a versão mais recente no pub.dev
  firebase_core: ^3.8.0
  path_provider: ^2.0.11
  image_picker: ^1.1.2
  firebase_storage: ^12.3.6
  uuid: ^4.5.1
  flutter_markdown: ^0.7.4+1
  flutter_svg: ^2.0.15


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1
  
flutter:
  uses-material-design: true

  assets:
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600


# flutter_icons:
#   android: "launcher_icon"
#   ios: true
#   image_path: "assets/icons/icon.png"
#   adaptive_icon_background: "#42a5f5"
#   adaptive_icon_foreground: "assets/icons/icon-foreground.png"