// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiNJ22Oepbj0I8GN2WUBs0UJ9cEI-r__o',
    appId: '1:876356170044:web:d7a943d97979595d51ee39',
    messagingSenderId: '876356170044',
    projectId: 'kusukamoto-563fe',
    authDomain: 'kusukamoto-563fe.firebaseapp.com',
    storageBucket: 'kusukamoto-563fe.firebasestorage.app',
    measurementId: 'G-BWDEYQG3TY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIs-IOZSs0khZmuI5ghSnYL5oXQ2WyiMY',
    appId: '1:876356170044:android:98e5fc3d07bbddad51ee39',
    messagingSenderId: '876356170044',
    projectId: 'kusukamoto-563fe',
    storageBucket: 'kusukamoto-563fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtk6zClwwTS_Ci_CazSWvd6LjLdVEqB9s',
    appId: '1:876356170044:ios:6dac4fea8055b0fb51ee39',
    messagingSenderId: '876356170044',
    projectId: 'kusukamoto-563fe',
    storageBucket: 'kusukamoto-563fe.firebasestorage.app',
    androidClientId: '876356170044-7ulqghhpfsvtc437ofgikpfsf9ph8eno.apps.googleusercontent.com',
    iosClientId: '876356170044-h30thhm8u8jto33ih929o5skunh5oipq.apps.googleusercontent.com',
    iosBundleId: 'com.example.kusukaMoto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtk6zClwwTS_Ci_CazSWvd6LjLdVEqB9s',
    appId: '1:876356170044:ios:6dac4fea8055b0fb51ee39',
    messagingSenderId: '876356170044',
    projectId: 'kusukamoto-563fe',
    storageBucket: 'kusukamoto-563fe.firebasestorage.app',
    androidClientId: '876356170044-7ulqghhpfsvtc437ofgikpfsf9ph8eno.apps.googleusercontent.com',
    iosClientId: '876356170044-h30thhm8u8jto33ih929o5skunh5oipq.apps.googleusercontent.com',
    iosBundleId: 'com.example.kusukaMoto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiNJ22Oepbj0I8GN2WUBs0UJ9cEI-r__o',
    appId: '1:876356170044:web:069d16b9e211a2af51ee39',
    messagingSenderId: '876356170044',
    projectId: 'kusukamoto-563fe',
    authDomain: 'kusukamoto-563fe.firebaseapp.com',
    storageBucket: 'kusukamoto-563fe.firebasestorage.app',
    measurementId: 'G-HNHCWE0Z6V',
  );
}
