// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJ0lSIXLt2F5UoRbpQ7JgEBWQhct2nYz0',
    appId: '1:589405166746:web:ba7570429992c91459d323',
    messagingSenderId: '589405166746',
    projectId: 'kusukamoto-51ee7',
    authDomain: 'kusukamoto-51ee7.firebaseapp.com',
    storageBucket: 'kusukamoto-51ee7.firebasestorage.app',
    measurementId: 'G-Y8901Q7NNV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv8YdJK9dAyQuV_qBVSnh-8D_9OpEpXHk',
    appId: '1:589405166746:android:bfbe77635179215459d323',
    messagingSenderId: '589405166746',
    projectId: 'kusukamoto-51ee7',
    storageBucket: 'kusukamoto-51ee7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDn_fJhEAPQxaXtEAv3OzremsresEZ68AY',
    appId: '1:589405166746:ios:686e5c4a9cdc1e8e59d323',
    messagingSenderId: '589405166746',
    projectId: 'kusukamoto-51ee7',
    storageBucket: 'kusukamoto-51ee7.firebasestorage.app',
    iosBundleId: 'com.example.kusukaMoto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDn_fJhEAPQxaXtEAv3OzremsresEZ68AY',
    appId: '1:589405166746:ios:686e5c4a9cdc1e8e59d323',
    messagingSenderId: '589405166746',
    projectId: 'kusukamoto-51ee7',
    storageBucket: 'kusukamoto-51ee7.firebasestorage.app',
    iosBundleId: 'com.example.kusukaMoto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJ0lSIXLt2F5UoRbpQ7JgEBWQhct2nYz0',
    appId: '1:589405166746:web:61f3756df6b0d8e859d323',
    messagingSenderId: '589405166746',
    projectId: 'kusukamoto-51ee7',
    authDomain: 'kusukamoto-51ee7.firebaseapp.com',
    storageBucket: 'kusukamoto-51ee7.firebasestorage.app',
    measurementId: 'G-HNTHKGFP24',
  );
}
